/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ApiCaptureRouteImport } from './routes/api.capture'
import { Route as ApiCompassRouteImport } from './routes/api.compass'
import { Route as ApiConfigRouteImport } from './routes/api.config'
import { Route as ApiSyncRouteImport } from './routes/api.sync'
import { Route as ApiWeatherRouteImport } from './routes/api.weather'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ClassesIndexRouteImport } from './routes/classes.index'
import { Route as ClassesCourseIdRouteImport } from './routes/classes.$courseId'
import { Route as ApiAuthPasscodeRouteImport } from './routes/api.auth.passcode'
import { Route as ApiCronSyncRouteImport } from './routes/api.cron.sync'
import { Route as ApiGoogleAuthRouteImport } from './routes/api.google.auth'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api.google.callback'
import { Route as ApiGoogleStatusRouteImport } from './routes/api.google.status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaptureRoute = ApiCaptureRouteImport.update({
  id: '/api/capture',
  path: '/api/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompassRoute = ApiCompassRouteImport.update({
  id: '/api/compass',
  path: '/api/compass',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherRoute = ApiWeatherRouteImport.update({
  id: '/api/weather',
  path: '/api/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesCourseIdRoute = ClassesCourseIdRouteImport.update({
  id: '/classes/$courseId',
  path: '/classes/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasscodeRoute = ApiAuthPasscodeRouteImport.update({
  id: '/api/auth/passcode',
  path: '/api/auth/passcode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncRoute = ApiCronSyncRouteImport.update({
  id: '/api/cron/sync',
  path: '/api/cron/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleAuthRoute = ApiGoogleAuthRouteImport.update({
  id: '/api/google/auth',
  path: '/api/google/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleStatusRoute = ApiGoogleStatusRouteImport.update({
  id: '/api/google/status',
  path: '/api/google/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/api/capture': typeof ApiCaptureRoute
  '/api/compass': typeof ApiCompassRoute
  '/api/config': typeof ApiConfigRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/weather': typeof ApiWeatherRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/classes/$courseId': typeof ClassesCourseIdRoute
  '/classes/': typeof ClassesIndexRoute
  '/api/auth/passcode': typeof ApiAuthPasscodeRoute
  '/api/cron/sync': typeof ApiCronSyncRoute
  '/api/google/auth': typeof ApiGoogleAuthRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/status': typeof ApiGoogleStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/api/capture': typeof ApiCaptureRoute
  '/api/compass': typeof ApiCompassRoute
  '/api/config': typeof ApiConfigRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/weather': typeof ApiWeatherRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/classes/$courseId': typeof ClassesCourseIdRoute
  '/classes': typeof ClassesIndexRoute
  '/api/auth/passcode': typeof ApiAuthPasscodeRoute
  '/api/cron/sync': typeof ApiCronSyncRoute
  '/api/google/auth': typeof ApiGoogleAuthRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/status': typeof ApiGoogleStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/api/capture': typeof ApiCaptureRoute
  '/api/compass': typeof ApiCompassRoute
  '/api/config': typeof ApiConfigRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/weather': typeof ApiWeatherRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/classes/$courseId': typeof ClassesCourseIdRoute
  '/classes/': typeof ClassesIndexRoute
  '/api/auth/passcode': typeof ApiAuthPasscodeRoute
  '/api/cron/sync': typeof ApiCronSyncRoute
  '/api/google/auth': typeof ApiGoogleAuthRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/status': typeof ApiGoogleStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/settings'
    | '/signin'
    | '/api/capture'
    | '/api/compass'
    | '/api/config'
    | '/api/sync'
    | '/api/weather'
    | '/auth/callback'
    | '/classes/$courseId'
    | '/classes/'
    | '/api/auth/passcode'
    | '/api/cron/sync'
    | '/api/google/auth'
    | '/api/google/callback'
    | '/api/google/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/settings'
    | '/signin'
    | '/api/capture'
    | '/api/compass'
    | '/api/config'
    | '/api/sync'
    | '/api/weather'
    | '/auth/callback'
    | '/classes/$courseId'
    | '/classes'
    | '/api/auth/passcode'
    | '/api/cron/sync'
    | '/api/google/auth'
    | '/api/google/callback'
    | '/api/google/status'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/settings'
    | '/signin'
    | '/api/capture'
    | '/api/compass'
    | '/api/config'
    | '/api/sync'
    | '/api/weather'
    | '/auth/callback'
    | '/classes/$courseId'
    | '/classes/'
    | '/api/auth/passcode'
    | '/api/cron/sync'
    | '/api/google/auth'
    | '/api/google/callback'
    | '/api/google/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  ApiCaptureRoute: typeof ApiCaptureRoute
  ApiCompassRoute: typeof ApiCompassRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiSyncRoute: typeof ApiSyncRoute
  ApiWeatherRoute: typeof ApiWeatherRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ClassesCourseIdRoute: typeof ClassesCourseIdRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
  ApiAuthPasscodeRoute: typeof ApiAuthPasscodeRoute
  ApiCronSyncRoute: typeof ApiCronSyncRoute
  ApiGoogleAuthRoute: typeof ApiGoogleAuthRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
  ApiGoogleStatusRoute: typeof ApiGoogleStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/capture': {
      id: '/api/capture'
      path: '/api/capture'
      fullPath: '/api/capture'
      preLoaderRoute: typeof ApiCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compass': {
      id: '/api/compass'
      path: '/api/compass'
      fullPath: '/api/compass'
      preLoaderRoute: typeof ApiCompassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather': {
      id: '/api/weather'
      path: '/api/weather'
      fullPath: '/api/weather'
      preLoaderRoute: typeof ApiWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$courseId': {
      id: '/classes/$courseId'
      path: '/classes/$courseId'
      fullPath: '/classes/$courseId'
      preLoaderRoute: typeof ClassesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/passcode': {
      id: '/api/auth/passcode'
      path: '/api/auth/passcode'
      fullPath: '/api/auth/passcode'
      preLoaderRoute: typeof ApiAuthPasscodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync': {
      id: '/api/cron/sync'
      path: '/api/cron/sync'
      fullPath: '/api/cron/sync'
      preLoaderRoute: typeof ApiCronSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/auth': {
      id: '/api/google/auth'
      path: '/api/google/auth'
      fullPath: '/api/google/auth'
      preLoaderRoute: typeof ApiGoogleAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/status': {
      id: '/api/google/status'
      path: '/api/google/status'
      fullPath: '/api/google/status'
      preLoaderRoute: typeof ApiGoogleStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  ApiCaptureRoute: ApiCaptureRoute,
  ApiCompassRoute: ApiCompassRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiSyncRoute: ApiSyncRoute,
  ApiWeatherRoute: ApiWeatherRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ClassesCourseIdRoute: ClassesCourseIdRoute,
  ClassesIndexRoute: ClassesIndexRoute,
  ApiAuthPasscodeRoute: ApiAuthPasscodeRoute,
  ApiCronSyncRoute: ApiCronSyncRoute,
  ApiGoogleAuthRoute: ApiGoogleAuthRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
  ApiGoogleStatusRoute: ApiGoogleStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
